### ISSUE TITLE
[FEATURE] Some feature that could be cool

### ISSUE THREAD

**Issue by NeverlandSMP** [Lauriichan/Wildcard#7]
monthly wildcard? not sure if it already has it but I have not seen it yet but the ablity for the whitelist per to expire after 30 days or so

**Comment by Lauriichan** [comment]
No that's currently not added and not really the purpose of this plugin.
This plugin was more for content creators to provide keys for their viewers to join onto the server without much trouble.
Your purpose sounds more like you would need to pay to get on the server which is not the purpose of this plugin.

If this is not the case then you can explain why you need that feature.
But in general I'm not supporting people that try to lock their users away behind a paywall

**Comment by NeverlandSMP** [comment]
ahhh ok nevermind then I was going to do a think where I stream but I want everything I make to be donated to a charity and there for it would have been easier to link it to donating instead of doing subs and having the send in the money later as twitch only lets you take out in 100$ sets so sub server but not sub server was the idea but I understand where you are coming from thank you for reading my suggestion

**Comment by Lauriichan** [comment]
So something which is a pretty neat idea however is to do a subserver connected directly to twitch yeah.
However for that to really work there would be the need for twitch integration.

As of now Wildcard is not a good solution for that because its not connected to twitch or anything
And second because of how wildcards work here.
A wildcard can be created for a player and that player gives that wildcard away.
That wildcard is can expire yes, however the players that used the wildcard can't.
Adding multiple wildcards to one player would require a lot of changes to the current code.

However in future I might create a mod which hooks into twitch to allow subscribers because that Idea is something different in my opinion
